# Generated by Django 4.0.4 on 2022-11-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carosel_id', models.IntegerField(null=True)),
                ('data', models.TextField()),
                ('image', models.TextField()),
                ('created_at', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_id', models.IntegerField(null=True)),
                ('stamp', models.IntegerField()),
                ('created_at', models.TimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Event_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='stock',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='main.category'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.IntegerField(null=True)),
                ('quantity', models.IntegerField()),
                ('memo', models.TextField()),
                ('made', models.BooleanField()),
                ('pickup', models.BooleanField()),
                ('created_at', models.TimeField(null=True)),
                ('menu', models.ManyToManyField(related_name='Menu', to='main.menu')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Menu_price', to='main.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_id', models.IntegerField(null=True)),
                ('created_at', models.TimeField(null=True)),
                ('carosel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Carosel', to='main.carosel')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='main.event')),
            ],
        ),
    ]
