# Generated by Django 4.0.4 on 2022-11-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carosel',
            name='Carosel_id',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='Coupon_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Event_id',
        ),
        migrations.RemoveField(
            model_name='home',
            name='Home_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Menu_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_id',
        ),
    ]
